### ISSUE TITLE
How to use this what exact input i have to provide to run this project and see output 

### ISSUE THREAD

**Issue by jhavishal10** [jeltsch/incremental-computing#1]
I have clone your project in my device and i am working on some research in incremental Computation and your project can help me alot i checked your darcshub repo too but not able which .hs file i have to run as it is showing some errors and what input and libraries do i need to import please help me out .

**Comment by jhavishal10** [comment]
can you please help me to get that waht input the program needs to show the incremental computation

**Comment by jeltsch** [comment]
Hi, @jhavishal10! The `incremental-computing` package contains just a library; so there is no program to run. Furthermore, it’s still very much work in progress. Previous versions of `incremental-computing` used an approach very different from what the current version follows. The previous approach is described in the paper “Purely functional incremental computing”, which is published in the proceedings of SBLP ’16; the current approach is explained in the talk I gave at the Haskell eXchange 2017, and a video recording of this talk should be available. Hope that helps.

**Comment by jhavishal10** [comment]
Thanks for making a reply and kind gesture..., as haskell has a very very small community and i am new to this i am facing a lot of problems , i will check your video and paper and give you an update in a while  till then  can you  help me give me a syntax or program in which i want to just import your current library (most updated one on the darshub) and give inputs accordingly because i want to explore things about incremental computation and i don't know how to use your library and neither a good documentation is available .

**Comment by jhavishal10** [comment]
and please provide the links of the resources that  you are talking about

**Comment by jhavishal10** [comment]
![image](https://user-images.githubusercontent.com/24814854/67977883-f29c1d00-fc3e-11e9-8998-66e6e1e6627f.png)

**Comment by jeltsch** [comment]
Hi, @jhavishal10!

I’ll send you the paper about the first approach and the slides of the talk about the second approach per e-mail.

Note, however, that both approaches use advanced features of Haskell, especially type system features; so if you’re new to Haskell you’ll likely have trouble understanding the code. Unfortunately, I don’t really have the time to assist you in studying these incremental computing approaches.

Please note also that especially the new approach is still very much work in progress. I’d say that perhaps 30 % of the whole story are implemented. I plan to implement the rest at some point in time, but currently this library is by no means complete (and, yes, it’s also not documented yet, because things may still change considerably). In one or two years, the situation might be much better, but now is not yet a good time to study this new incremental computing approach, I’m afraid.

**Comment by jhavishal10** [comment]
Thankyou again , i will try to run this library for some basic stuffs please proivde me the slides of your presentation and your first approach paper on tha mail ID:    jhavishal10@gmail.com
